
/* CREATING THE ACCESS FO R THE SELECT ROLE */
CREATE ROLE SELECT_ACCESS_USER;

/*GRANTING THE ADMIN SCHEMA SALES TO SELECT_ACCESS_USER ROLE */
GRANT SELECT ON SALES TO SELECT_ACCESS_USER;

/*CREATING A USER FOR THE SAME */
CREATE USER RIKA IDENTIFIED BY  Abismruta1997
ACCOUNT UNLOCK

/*ASSIGNING THE ROLE TO THE USER */
GRANT SELECT_ACCESS_USER TO RIKA

/*NOW WE CAN PROVIDE RIKA THE CREATE SESSION ACCESS TO ACCESS THE SCHMA */
GRANT CREATE SESSION TO RIKA;