/*SHOW USERS AFTER SIGNING IN*/

SHOW USER;--SHOWING ALL THE USERS

SELECT * FROM ALL_USERS;--CHECKING FOR ALL THE USER IN THE SCOPE

SELECT * FROM ADMIN.SALES;--CAN ACCESS THE SELECTR FROM THE ADMIN SCHEMA TABLE  BUT NO OTHER ACTION

DELETE FROM ADMIN.SALES WHERE TOTAL_AMOUNT=1760;;--CAN ACCESS THE SELECTR FROM THE ADMIN SCHEMA TABLE  BUT NO OTHER ACTION