SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES ADD STORES_ID NUMBER;

UPDATE EMPLOYEES SET STORES_ID=3 WHERE ENAME IN ('KING','BLAKE','CLARK')

UPDATE EMPLOYEES SET STORES_ID=2 WHERE JOB='SALESMAN'

UPDATE EMPLOYEES SET STORES_ID=4 WHERE JOB='CLERK'

UPDATE EMPLOYEES SET STORES_ID=4 WHERE JOB='ANALYST'

UPDATE EMPLOYEES SET STORES_ID=1 WHERE JOB='MANAGER'

SELECT * FROM EMPLOYEES WHERE ENAME IN ('KING','BLAKE','CLARK')

SELECT * FROM EMPLOYEES WHERE JOB='SALESMAN'

SELECT * FROM EMPLOYEES WHERE JOB='CLERK'

ALTER TABLE EMPLOYEES MODIFY STORES_ID NUMBER NOT NULL

SELECT 