

SELECT * FROM WFMTDB;

/*ALL ALTER COMMAND RELATED TO THE COLUMN */

/*CREATING A VIRTUAL COLUMN TO PERFORM ALTERATION */

SELECT * FROM WFMTDB;

ALTER TABLE WFMTDB ADD MODIFIED_CP GENERATED ALWAYS AS (SNE_ID*2)

ALTER TABLE WFMTDB MODIFY MODIFIED_CP GENERATED ALWAYS AS (SNE_ID*3)

ALTER TABLE WFMTDB RENAME COLUMN MODIFIED_CP TO NEW_MODIFIED_CP;

ALTER TABLE WFMTDB DROP COLUMN NEW_MODIFIED_CP;


/* ALL ALTER RELATED TO CONSTRAINT */

ALTER TABLE WFMTDB ADD CONSTRAINT PRIMARY_WFMT PRIMARY KEY (SNE_ID) ;

ALTER TABLE WFMTDB ADD CONSTRAINT SCHEME_NUMBER_UNIQUE UNIQUE (SCHEME_NUMBER);

ALTER TABLE WFMTDB DISABLE CONSTRAINT SCHEME_NUMBER_UNIQUE

ALTER TABLE WFMTDB ENABLE CONSTRAINT SCHEME_NUMBER_UNIQUE

ALTER TABLE WFMTDB DROP CONSTRAINT PRIMARY_WFMT;

