
SELECT * FROM SALES;

DESC SALES;

ALTER TABLE SALES RENAME COLUMN  QUANTITY TO QUANTITY_VALUE;

ALTER TABLE SALES ADD DIV_AMOUNT AS (TOTAL_AMOUNT/TAX_AMOUNT);

ALTER TABLE SALES DROP COLUMN DIV_AMOUNT;

SELECT USER FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT  GREATEST(10,20,5) FROM DUAL;
SELECT CEIL(56.7892) FROM DUAL;

SELECT  GREATEST(10,20,5),CEIL(3.143) ,ROUND(49.897,1),SQRT(4096),POWER(64,2) FROM DUAL;


SELECT DECODE(50,10,'TEN',50,'FIFTY',20,'TWENTY') FROM DUAL;

SELECT * FROM CUSTOMER;

--INNER JOIN--

SELECT S.SALES_DATE,C.FIRST_NAME
FROM SALES S INNER JOIN CUSTOMER C
ON S.CUSTOMER_ID=C.CUSTOMER_ID;


---ALTERNATE INNERJOIN COMMAND---

SELECT S.SALES_DATE,C.FIRST_NAME
FROM SALES S ,CUSTOMER C
WHERE S.CUSTOMER_ID=C.CUSTOMER_ID;


--EXAMPLE OF LEFT OUTER-JOIN----

SELECT DISTINCT S.SALES_DATE,S.PRODUCT_ID,S.SALES_AMOUNT,C.FIRST_NAME,C.LAST_NAME FROM 
SALES S ,CUSTOMER C
WHERE S.CUSTOMER_ID=C.CUSTOMER_ID(+);


SELECT DISTINCT S.SALES_DATE,S.PRODUCT_ID,S.SALES_AMOUNT,C.FIRST_NAME,C.LAST_NAME FROM 
SALES S LEFT OUTER JOIN CUSTOMER C
ON S.CUSTOMER_ID=C.CUSTOMER_ID;

--RIGHT-OUTER-JOIN

DESC SALES;

DESC CUSTOMER;

SELECT * FROM CUSTOMER;

SELECT SALES.SALES_DATE, SALES.TAX_AMOUNT,CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME
FROM SALES,CUSTOMER
WHERE  SALES.CUSTOMER_ID (+) =CUSTOMER.CUSTOMER_ID


---NATURAL JOIN-----


SELECT SALES.SALES_DATE, SALES.TAX_AMOUNT,CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME
FROM SALES NATURAL JOIN CUSTOMER

--CROSS JOIN---

SELECT SALES.SALES_DATE, SALES.TAX_AMOUNT,CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME
FROM SALES CROSS JOIN CUSTOMER


--FULL OUTER JOIN----

SELECT S.SALES_DATE, C.FIRST_NAME 
FROM SALES S FULL OUTER JOIN CUSTOMER C 
ON S.CUSTOMER_ID=C.CUSTOMER_ID;

SELECT * FROM CUSTOMER;

