
/*SOLVING THE SAME EQUI AND NON EQUII PROBLEM USING THE CASE STATEMENT*/

SELECT EMP.*,
(  
CASE 
    WHEN SAL <= 1000 THEN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE HIGHEST_SAL=1000)
    WHEN SAL <= 2000 THEN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE HIGHEST_SAL > 1000 AND HIGHEST_SAL<=2000)
    WHEN SAL <= 3000 THEN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE HIGHEST_SAL > 2000 AND HIGHEST_SAL<=3000)
    WHEN SAL <= 4000 THEN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE HIGHEST_SAL > 3000 AND HIGHEST_SAL<=4000)
    WHEN SAL <= 5000 THEN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE HIGHEST_SAL > 4000 AND HIGHEST_SAL<=5000)
    ELSE 'NO COMMENT'
END
) GRADE
FROM EMP

SELECT  E.*,
(
CASE 
    WHEN E.SAL>2000 THEN 'BIG SHORT'
    ELSE 'NEED TO EARN MORE '
END
) AS EMP_COMMENT
FROM EMP E
