
CREATE TABLE USER_WFMT(
    USER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50),
    CONSTRAINT USER_WFMT_PK PRIMARY KEY (USER_ID)
)

CREATE TABLE PROJECT_WFMT(
    PROJECT_ID NUMBER NOT NULL,
    PROJECT_NAME VARCHAR2(50) NOT NULL,
    CREATOR NUMBER NOT NULL,
    CONSTRAINT PROJECT_WFMT_PK PRIMARY KEY (PROJECT_ID),
    CONSTRAINT PROJECT_WFMT_FK FOREIGN KEY (CREATOR) REFERENCES USER_WFMT(USER_ID)
)

INSERT INTO USER_WFMT(USER_ID,USERNAME) VALUES (1006,'RIKUNU')

INSERT INTO PROJECT_WFMT(PROJECT_ID,PROJECT_NAME,CREATOR) VALUES (4444,'WFMT_TO_SRIMS_CONNECT',1006)


SELECT * FROM USER_WFMT

SELECT * FROM PROJECT_WFMT

-- CREATE TABLE PROJECT_USER_WFMT(
--     PROJECT_USER_WFMT_ID NUMBER NOT NULL,
--     USER_ID NUMBER NOT NULL REFERENCES USER_WFMT(USER_ID) ON DELETE CASCADE,
--     PROJECT_ID NUMBER NOT NULL REFERENCES PROJECT_WFMT(PROJECT_ID) ON DELETE CASCADE ,
--     CONSTRAINT PROJECT_USER_WFMT_PK PRIMARY KEY (PROJECT_USER_WFMT_ID)
-- )

--CREATING A COMPOSITE KEY BASED ON THE PRIMARYU KEY OF THE USER_WFMT TABLE AND PROJECT_WFMT TABLE AND REFERNECE THEM  AS FOREIGN KEY --
--NOW CREATING THE COMPOSITE KEY BASED ON THAT PRIMARY KEY WHICH IS REFERENCE BY THE FOREIGN KEY----  

CREATE TABLE PROJECT_USER_WFMT(
    PROJECT_ID  NOT NULL REFERENCES PROJECT_WFMT (PROJECT_ID) ON DELETE CASCADE,
    USER_ID  NOT NULL REFERENCES USER_WFMT (USER_ID) ON DELETE CASCADE,
    CONSTRAINT PROJECT_USER_WFMT_PK PRIMARY KEY (PROJECT_ID,USER_ID)
)

DESCRIBE PROJECT_USER_WFMT

INSERT INTO PROJECT_USER_WFMT VALUES (7777,1001);

SELECT * FROM PROJECT_USER_WFMT;

DROP TABLE PROJECT_USER_WFMT;

DELETE FROM USER_WFMT WHERE USER_ID=1002

DELETE FROM PROJECT_WFMT WHERE PROJECT_ID=8888

SELECT * FROM PROJECT_USER_WFMT

SELECT * FROM PROJECT_USER_WFMT;

SELECT * FROM USER_WFMT ORDER BY USER_ID;

SELECT * FROM PROJECT_WFMT ORDER BY PROJECT_ID;