
SELECT * FROM EMPLOYEE,DEPART

SELECT * FROM EMPLOYEE CROSS JOIN DEPART

SELECT * FROM EMP NATURAL JOIN DEPT 

SELECT * FROM DEPART

SELECT * FROM EMPLOYEE

SELECT EMPNO,ENAME,LOC
FROM EMPLOYEE E JOIN DEPART D
USING(DEPT,DEPTNO)

SELECT * FROM EMP

SELECT * FROM DEPT

ALTER TABLE DEPART ADD DEPT NUMBER

ALTER TABLE EMPLOYEE ADD DEPTNO NUMBER;

UPDATE DEPART SET DEPT=DEPTNO

UPDATE EMPLOYEE SET DEPTNO=DEPT

SELECT EMPNO,DNAME,LOC,DEPTNO
FROM EMP E JOIN DEPT D
USING(DEPTNO)


CREATE TABLE JOB_GRADE(
    GRADE_LEVEL VARCHAR2(10) NOT NULL,
    LOWEST_SAL NUMBER NOT NULL,
    HIGHEST_SAL NUMBER NOT NULL
)

INSERT ALL 
    -- INTO JOB_GRADE (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) VALUES ('A',0,1000)
    -- INTO JOB_GRADE (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) VALUES ('B',1000,2000)
    -- INTO JOB_GRADE (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) VALUES ('C',2000,3000)
    -- INTO JOB_GRADE (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) VALUES ('D',3000,4000)
    INTO JOB_GRADE (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) VALUES ('E',4000,5000)
SELECT * FROM DUAL

SELECT * FROM JOB_GRADE;

UPDATE JOB_GRADE SET GRADE_LEVEL='D' WHERE  LOWEST_SAL=3000

SELECT * FROM EMP;

SELECT E.*,GRADE_LEVEL,
FROM EMP E, JOB_GRADE 
WHERE GRADE_LEVEL IN (SELECT GRADE_LEVEL FROM JOB_GRADE WHERE E.SAL >=LOWEST_SAL AND E.SAL <=HIGHEST_SAL) 

SELECT E.*,GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL
FROM EMP E, JOB_GRADE 
WHERE SAL BETWEEN LOWEST_SAL AND HIGHEST_SAL



SELECT GRADE_LEVEL FROM JOB_GRADE WHERE 4890 >=LOWEST_SAL AND 4890 <=HIGHEST_SAL