CREATE OR REPLACE PROCEDURE EMP_DEPT_PROC_NEW
(
    OBJ_NAME IN VARCHAR2
)
IS 
    OBJ_TYPE ALL_OBJECTS.OBJECT_TYPE%TYPE;
BEGIN
    SELECT OBJECT_TYPE INTO OBJ_TYPE
    FROM ALL_OBJECTS WHERE OBJECT_NAME=OBJ_NAME;
    DBMS_OUTPUT.PUT_LINE(OBJ_TYPE);
    DBMS_OUTPUT.PUT_LINE(OBJ_NAME);
    EXECUTE IMMEDIATE 'DROP ' || OBJ_TYPE || OBJ_NAME
    -- DBMS_OUTPUT.PUT_LINE('DROP ' || OBJ_TYPE || OBJ_NAME);
    DBMS_OUTPUT.PUT_LINE('ALL TASK EXECUTED SUCCESSFULLY');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END EMP_DEPT_PROC_NEW ;

