SELECT * FROM STORES_EMP1 ORDER BY STORES_ID;

CREATE UNIQUE INDEX STORES_ID_IDX ON STORES_EMP1(STORES_ID);

CREATE TABLE STORES_EMP1 AS(
    SELECT * FROM STORES_EMP
)

ALTER INDEX STORES_ID_IDX
REBUILD COMPUTE STATISTICS 

DROP INDEX STORES_ID_IDX

ALTER INDEX STORES_ID_IDX UNIQUE


SELECT STORES_ID, CITY, COUNT(*)
FROM STORES_EMP1
GROUP BY STORES_ID,CITY

SELECT STORES_ID, CITY, COUNT(1),COUNT(2)
FROM STORES_EMP1
GROUP BY STORES_ID,CITY