
CREATE TABLE LEASE_RECORD
(
    LEASE_NUMBER NUMBER,
    ADDRESS VARCHAR2(50),
    LEASE_EXPIRATION INTERVAL YEAR TO MONTH
)

INSERT INTO LEASE_RECORD (LEASE_NUMBER,ADDRESS,LEASE_EXPIRATION) 
VALUES (120,'VEE-ESS BUILDING BANGALORE', INTERVAL '10-2' YEAR TO MONTH )

SELECT * FROM LEASE_RECORD;

INSERT INTO LEASE_RECORD (LEASE_NUMBER,ADDRESS,LEASE_EXPIRATION) 
VALUES (120,'VEE-ESS BUILDING BANGALORE', INTERVAL '100' MONTH )

UPDATE LEASE_RECORD SET LEASE_NUMBER=130 WHERE LEASE_EXPIRATION=INTERVAL '100' MONTH 

SELECT * FROM LEASE_RECORD;

INSERT INTO LEASE_RECORD (LEASE_NUMBER,ADDRESS,LEASE_EXPIRATION) 
VALUES (120,'VEE-ESS BUILDING BANGALORE', INTERVAL '99' YEAR )

SELECT * FROM LEASE_RECORD;

ALTER TABLE LEASE_RECORD MODIFY LEASE_EXPIRATION INTERVAL YEAR(3) TO MONTH

DESCRIBE LEASE_RECORD;

INSERT INTO LEASE_RECORD (LEASE_NUMBER,ADDRESS,LEASE_EXPIRATION) 
VALUES (120,'VEE-ESS BUILDING BANGALORE', INTERVAL '111' YEAR(3) )

SELECT * FROM LEASE_RECORD;


SELECT * FROM LEASE_RECORD WHERE LEASE_EXPIRATION=INTERVAL '111' YEAR(3)
