
CREATE OR REPLACE VIEW EMP_JOIN_VIEW AS
SELECT E.ENAME,E.JOB,E.SAL,D.LOC FROM WKSP_WFMTDBBINDS.EMPLOYEE E ,WKSP_WFMTDBBINDS.DEPART D
WHERE E.DEPT=D.DEPTNO(+) 
AND D.LOC='DALLAS'

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL

CREATE INDEX EMP_IDX ON EMPLOYEE(ENAME)

DESCRIBE EMP_IDX



SELECT E.ENAME,E.JOB,E.SAL,E.LOC
FROM (SELECT * FROM EMP,DEPT) E
WHERE E.LOC='DALLAS'

SELECT E.ENAME,E.JOB,E.SAL,D.LOC
FROM (SELECT * FROM EMPLOYEE) E,(SELECT * FROM DEPART) D
WHERE E.DEPT=D.DEPTNO(+) 
AND D.LOC='DALLAS'
