SELECT * FROM EXISTING_CUSTOMERS;

SELECT * FROM NEW_CUSTOMERS;

DESC EXISTING_CUSTOMERS

DESC NEW_CUSTOMERS

/*
MERGING ALL THE EXISTING CUSTOMER TO NEW CUSTOMER WITHOUT WHERE CLAUSE 
SO THAT THE COLUMN MATCH SHOULD BE UPDATED 
AND THE COLUMN NOT MATCHING WILL BE INSERTED 
*/

SELECT * FROM  EXISTING_CUSTOMERS;

SELECT * FROM NEW_CUSTOMERS;

MERGE INTO EXISTING_CUSTOMERS DEST
    USING NEW_CUSTOMERS SRC
    ON (DEST.CUSTOMER_ID=SRC.CUSTOMER_ID)
WHEN MATCHED THEN
    UPDATE SET 
        DEST.FIRST_NAME=SRC.FIRST_NAME,
        DEST.LAST_NAME=SRC.LAST_NAME,
        DEST.ADDRESS_STATE=SRC.ADDRESS_STATE,
        DEST.EMAIL_ADDRESS=SRC.EMAIL_ADDRESS
WHEN NOT MATCHED THEN
    INSERT (DEST.CUSTOMER_ID,DEST.FIRST_NAME,DEST.LAST_NAME,DEST.ADDRESS_STATE,DEST.EMAIL_ADDRESS)
    VALUES (SRC.CUSTOMER_ID,SRC.FIRST_NAME,SRC.LAST_NAME,SRC.ADDRESS_STATE,SRC.EMAIL_ADDRESS)

/* NOW MERGING THEM TOGETHER WITH A CONSDITION THAT  IF THE NAME IS TERSSA THEN DELETE THE COLUMN FROM DESTINATION TABLE */

MERGE INTO EXISTING_CUSTOMERS DEST
        USING NEW_CUSTOMERS SRC
        ON
        (
        DEST.CUSTOMER_ID=SRC.CUSTOMER_ID
        )
WHEN MATCHED THEN
        UPDATE SET 
                DEST.FIRST_NAME=SRC.FIRST_NAME,
                DEST.LAST_NAME=SRC.LAST_NAME,
                DEST.ADDRESS_STATE=SRC.ADDRESS_STATE,
                DEST.EMAIL_ADDRESS=SRC.EMAIL_ADDRESS
        DELETE 
                WHERE DEST.FIRST_NAME='Teresa'
WHEN NOT MATCHED THEN
        INSERT (DEST.CUSTOMER_ID,DEST.FIRST_NAME,DEST.LAST_NAME,DEST.ADDRESS_STATE,DEST.EMAIL_ADDRESS)
        VALUES(SRC.CUSTOMER_ID,SRC.FIRST_NAME,SRC.LAST_NAME,SRC.ADDRESS_STATE,SRC.EMAIL_ADDRESS)
        


SELECT * FROM EXISTING_CUSTOMERS;