
--SELECT * FROM SALES_HISTORY1 ORDER BY SALES_DATE;
--
--DELETE FROM SALES_HISTORY1 WHERE SALES_DATE IN ('09-FEB-15','10-FEB-15','11-FEB-15','12-FEB-15','13-FEB-15')

DELETE FROM SALES1 WHERE SALES_DATE IN ( '01-JAN-15','02-JAN-15','01-FEB-15')
--
--SELECT * FROM SALES1 ORDER BY SALES_DATE;
--
--UPDATE SALES1 SET ORDER_ID=1269 WHERE SALES_DATE='01-JAN-15'
--
DESC SALES1
--
SELECT * FROM SALES1 ORDER BY SALES_DATE;

SELECT * FROM SALES_HISTORY1
/* 
PERFORMING THE MERGING BETWEEN THE SALES_HISTORY1 WHICH IS A SYNONYM OF SALES_HISTORY AND SALES HISTORY IS SYNONYM OF SALES TABLE
*/

MERGE INTO SALES_HISTORY1  DEST
        USING SALES1 SRC
        ON
        (
             DEST.SALES_DATE=SRC.SALES_DATE
        )
WHEN MATCHED THEN
        UPDATE  SET 
                DEST.ORDER_ID=SRC.ORDER_ID,
                DEST.PRODUCT_ID=SRC.PRODUCT_ID,
                DEST.CUSTOMER_ID=SRC.CUSTOMER_ID,
                DEST.SALESPERSON_ID=SRC.SALESPERSON_ID
WHEN NOT MATCHED THEN
        INSERT (DEST.SALES_DATE,DEST.ORDER_ID,DEST.PRODUCT_ID,DEST.CUSTOMER_ID,DEST.SALESPERSON_ID)
        VALUES (SRC.SALES_DATE,SRC.ORDER_ID,SRC.PRODUCT_ID,SRC.CUSTOMER_ID,SRC.SALESPERSON_ID)
        