/*NVL FUNCTION */

SELECT ENAME,SAL,
(CASE
    WHEN NVL(COMM,0)=0 THEN 'NO DATA FOUND'
    ELSE TO_CHAR(NVL(COMM,0))
END) AS COMMS
FROM EMP

/* ALTERNATE APPROACH */
SELECT ENAME,SAL,DECODE(TO_CHAR(NVL(COMM,0)),'0','NO DATA FOUND',TO_CHAR(NVL(COMM,0)),TO_CHAR(NVL(COMM,0))) AS COMM
FROM EMP 

/*ALTERNATE APPROACH*/
SELECT ENAME,SAL,NVL(TO_CHAR(COMM),'NO_DATA_FOUND') AS COMMS
FROM EMP 

-- SELECT CONCAT('HELLO ','WORLD')FROM DUAL

--USAGE OF NVL2 FUNCTION-----
SELECT ENAME,SAL,NVL2(TO_CHAR(COMM),TO_CHAR(COMM),'NO_DATA_FOUND') AS COMMS
FROM EMP 




SELECT ENAME,LENGTH(ENAME) FROM EMP

SELECT ENAME,LENGTH(ENAME),NULLIF(LENGTH(ENAME),5)CHECK_OUT 
FROM EMP

/*USING THE NVL FUNCTION */

SELECT ENAME,LENGTH(ENAME),NVL(TO_CHAR(NULLIF(LENGTH(ENAME),5)),'LENGTH IS 5')CHECK_OUT 
FROM EMP

/*ALTERNATE APPROACH USING THE NVL2 FUNCTION  */

SELECT ENAME,LENGTH(ENAME),NVL2(TO_CHAR(NULLIF(LENGTH(ENAME),5)),TO_CHAR(NULLIF(LENGTH(ENAME),5)),'LENGTH IS 5')CHECK_OUT 
FROM EMP
