
SELECT * FROM SALES  WHERE ROWNUM IN (1,2,3,4)  ORDER BY SALES_DATE

SELECT * FROM SALES  WHERE ROWNUM <4  ORDER BY SALES_DATE



SELECT * FROM  SALES   ORDER BY SALES_DATE OFFSET 2 ROWS FETCH NEXT 5 ROWS ONLY

CREATE TABLE EMPLOYEES_1 AS
(
    SELECT EMPNO ,ENAME,JOB,HIREDATE,COMM FROM EMP ORDER BY EMPNO FETCH NEXT 4 ROWS ONLY
)


INSERT INTO EMPLOYEES_1 SELECT EMPNO ,ENAME,JOB,HIREDATE,COMM FROM EMP ORDER BY EMPNO OFFSET 4 ROWS FETCH NEXT 10 ROWS ONLY







SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES ADD STORES_ID NUMBER;

UPDATE EMPLOYEES SET STORES_ID=3 WHERE ENAME IN ('KING','BLAKE','CLARK')

UPDATE EMPLOYEES SET STORES_ID=2 WHERE JOB='SALESMAN'

UPDATE EMPLOYEES SET STORES_ID=4 WHERE JOB='CLERK'

UPDATE EMPLOYEES SET STORES_ID=4 WHERE JOB='ANALYST'

UPDATE EMPLOYEES SET STORES_ID=1 WHERE JOB='MANAGER'

SELECT * FROM EMPLOYEES WHERE ENAME IN ('KING','BLAKE','CLARK')

SELECT * FROM EMPLOYEES WHERE JOB='SALESMAN'

SELECT * FROM EMPLOYEES WHERE JOB='CLERK'

ALTER TABLE EMPLOYEES MODIFY STORES_ID NUMBER NOT NULL


CREATE TABLE EMPLOYEES_1 AS (
    SELECT EMPNO ,ENAME,JOB,HIREDATE,COMM FROM EMP ORDER BY EMPNO FETCH NEXT 4 ROWS ONLY
)


INSERT INTO EMPLOYEES_1 SELECT EMPNO ,ENAME,JOB,HIREDATE,COMM FROM EMP ORDER BY EMPNO OFFSET 4 ROWS FETCH NEXT 10 ROWS ONLY