
SELECT * FROM SALES;

SELECT * FROM CUSTOMER;

--creating the views for inner joined wfmt db--

CREATE VIEW SALE_CUST_VIEW AS
SELECT  S.ORDER_ID,S.SALESPERSON_ID,S.SALES_AMOUNT,C.REGION
FROM SALES S INNER JOIN CUSTOMER C
ON S.CUSTOMER_ID=C.CUSTOMER_ID;

SELECT * FROM SALE_CUST_VIEW;


--ALTERNATE APPROACH but here we are updating the VIEW COLUMN TO ADD FEW MORE RESULT---

CREATE OR REPLACE VIEW SALE_CUST_VIEW AS
SELECT  S.ORDER_ID,S.SALESPERSON_ID,S.SALES_AMOUNT,S.SALES_DATE,C.REGION
FROM SALES S ,CUSTOMER C
WHERE S.CUSTOMER_ID=C.CUSTOMER_ID;

SELECT * FROM SALE_CUST_VIEW;

--now Here i am updaing the view directly linked with customer table as i have the permission for the same ---

CREATE VIEW SALES_VIEW AS
SELECT S.SALES_DATE,S.ORDER_ID,S.CUSTOMER_ID,S.TAX_AMOUNT,S.TOTAL_AMOUNT
FROM SALES S


UPDATE SALES_VIEW SET TAX_AMOUNT=170 WHERE ORDER_ID=1269;

SELECT * FROM SALES_VIEW;



