select brick_id, weight, 
       row_number() over ( order by weight ) rn, 
       rank() over ( order by weight ) rk, 
       dense_rank() over ( order by weight ) dr
from   bricks;

UPDATE BRICKS SET WEIGHT=5
WHERE WEIGHT=2

COMMIT;


UPDATE BRICKS SET WEIGHT=2
WHERE WEIGHT=5

COMMIT;


SELECT * FROM BRICKS;


SELECT B.*,
LAG(WEIGHT)OVER(ORDER BY BRICK_ID) AS RESULT_VAR
FROM BRICKS B

SELECT B.*,
LAG(SHAPE)OVER(ORDER BY BRICK_ID) AS RESULT_VAR
FROM BRICKS B


SELECT B.*,
LEAD(WEIGHT)OVER(ORDER BY BRICK_ID) AS RESULT_VAR
FROM BRICKS B

SELECT B.*,
LEAD(SHAPE)OVER(ORDER BY BRICK_ID) AS RESULT_VAR
FROM BRICKS B

SELECT B.*,
-- FIRST_VALUE(SHAPE)OVER(ORDER BY BRICK_ID) AS FIRST_VAL,
LAST_VALUE(SHAPE)OVER(ORDER BY BRICK_ID
-- RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
) AS LAST_VAL
FROM BRICKS B

