SELECT * FROM STORES_EMPLOYEE;

BEGIN
        EXECUTE IMMEDIATE
        'CREATE INDEX STORES_EMPLOYEE_NEW_IDX ON STORES_EMPLOYEE(STORES_ID) COMPUTE STATISTICS';
        DBMS_OUTPUT.PUT_LINE('INDEX CREATED SUCCESSFULLY');

END;

SELECT ROWID,STORES_ID,CITY FROM STORES_EMPLOYEE WHERE STORES_ID=1004;

DELETE FROM STORES_EMPLOYEE
WHERE ROWID NOT IN (
SELECT MIN(ROWID)
FROM STORES_EMPLOYEE
GROUP BY STORES_ID
)

ALTER TABLE STORES_EMPLOYEE MODIFY STORES_ID NUMBER PRIMARY KEY