
/* INNER JOIN ON GROUP  BY AND HAVING CLAUSE */

SELECT E.EMPNO,E.ENAME,E.JOB,E.HIREDATE,D.DNAME, D.LOC,COUNT(*)
FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY E.EMPNO,E.ENAME,E.JOB,E.HIREDATE,D.DNAME, D.LOC
HAVING E.EMPNO > 7782


/* LEFT OUTER JOIN ON GROUP  BY AND HAVING CLAUSE */

SELECT E.EMPNO,E.ENAME,E.JOB,E.HIREDATE,D.DNAME, D.LOC,COUNT(*)
FROM EMP E LEFT OUTER JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY E.EMPNO,E.ENAME,E.JOB,E.HIREDATE,D.DNAME, D.LOC
HAVING AVG(E.EMPNO) > 7726.57 


SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='STORES_EMPLOYEE';

SELECT * FROM ALL_OBJECTS WHERE OBJECT_TYPE='INDEX' AND LAST_DDL_TIME BETWEEN TO_DATE('08-FEB-2022','DD-MM-YYYY') AND TO_DATE('10-FEB-2022','DD-MM-YYYY')