
CREATE SYNONYM EMP_PRAGMA_SYN FOR EMP_PRAGMA ; 

SELECT * FROM EMP_PRAGMA_SYN;

CREATE SEQUENCE EMP_PRAG_SEQ
 MINVALUE 10
 MAXVALUE 20
START WITH 10
INCREMENT BY 1
CACHE 10 ;

SELECT EMP_PRAG_SEQ.NEXTVAL FROM DUAL;
SELECT EMP_PRAG_SEQ.CURRVAL FROM DUAL;

CREATE OR REPLACE VIEW  EMP_PRAG_VIEW AS 
SELECT * FROM EMP_PRAGMA WHERE EMPNO>1006;

SELECT * FROM EMP_PRAG_VIEW;

GRANT ALL PRIVILEGES  ON EMP_PRAG_VIEW TO PRATEEK;

GRANT ALL PRIVILEGES  ON EMP_PRAG_VIEW TO ABISMRUTA WITH GRANT OPTION

CREATE  INDEX EMP_PRAGMA_INDEX  ON  EMP_PRAGMA (EMPNO) ;



