SELECT * FROM hr.employees

SELECT E1.EMPLOYEE_ID,E1.FIRST_NAME,E1.LAST_NAME,E1.MANAGER_ID,
(SELECT E2.FIRST_NAME FROM hr.employees E2 WHERE E2.EMPLOYEE_ID=E1.MANAGER_ID )
FROM hr.employees E1 
ORDER BY E1.EMPLOYEE_ID


SELECT E1.*,E2.FIRST_NAME 
FROM hr.employees E1 , hr.employees E2
WHERE E2.EMPLOYEE_ID=E1.MANAGER_ID

SELECT E1.*,E2.FIRST_NAME 
FROM hr.employees E1 , hr.employees E2
WHERE E2.EMPLOYEE_ID=E1.MANAGER_ID(+)

/* OR BY USING THE LEFT OUTER JOIN*/
SELECT E1.*,E2.FIRST_NAME 
FROM hr.employees E1 LEFT OUTER JOIN hr.employees E2
ON E2.EMPLOYEE_ID=E1.MANAGER_ID

SELECT * 
FROM EMPLOYEE E RIGHT JOIN DEPART D
ON E.DEPT=D.DEPTNO

SELECT * 
FROM EMPLOYEE E FULL JOIN DEPART D
ON E.DEPT=D.DEPTNO

SELECT * FROM 
DEPT D LEFT JOIN EMPLOYEE E
ON E.DEPT=D.DEPTNO


SELECT * 
FROM EMPLOYEE E ,DEPART D
WHERE E.DEPT(+)=D.DEPTNO

SELECT * FROM 
(SELECT * FROM EMP WHERE JOB='SALESMAN') E LEFT OUTER JOIN (SELECT * FROM DEPT) D
ON E.DEPTNO=D.DEPTNO

SELECT E.*,D.* FROM 
(SELECT * FROM DEPT) D  LEFT OUTER JOIN (SELECT * FROM EMP WHERE JOB='SALESMAN') E
ON E.DEPTNO=D.DEPTNO

SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,E.DEPTNO,D.DEPTNO,D.DNAME,D.LOC
FROM
(SELECT * FROM DEPT) D LEFT OUTER JOIN (SELECT * FROM EMP WHERE JOB='SALESMAN' ) E
ON E.DEPTNO=D.DEPTNO

SELECT EMP.EMPNO, EMP.ENAME , EMP.MGR FROM EMP 

SELECT E1.EMPNO,E1.ENAME,E1.MGR,
(SELECT EMP.ENAME FROM EMP WHERE EMPNO=E1.MGR) AS E_MGR_NAME
FROM EMP E1

SELECT E1.*,E2.ENAME 
FROM EMP E1 INNER JOIN EMP E2
ON E1.MGR=E2.EMPNO

SELECT E1.EMPNO,E1.ENAME,E1.MGR,E2.ENAME AS "MANAGER NAME"
FROM EMP E1 , EMP E2
WHERE E1.MGR=E2.EMPNO(+) 

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL