SELECT * FROM BRICKS;

SELECT B.*,
SUM(WEIGHT)OVER(ORDER BY BRICK_ID RANGE BETWEEN 2 PRECEDING AND CURRENT ROW)
FROM BRICKS B

SELECT B.*,
SUM(WEIGHT)OVER(ORDER BY BRICK_ID RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
FROM BRICKS B


SELECT B.*,
SUM(WEIGHT)OVER(ORDER BY COLOUR ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
FROM BRICKS B

