
CREATE TABLE EMPLOYEE_INFO(
    ENO NUMBER NOT NULL,
    ENAME VARCHAR2(50) NOT NULL,
    SAL NUMBER,
    CONSTRAINT EMPLOYEE_INFO_PK PRIMARY KEY (ENO),
    CONSTRAINT EMPLOYEE_INFO_CHECK CHECK ('SAL'>5000)
)

ALTER TABLE EMPLOYEE_INFO DROP CONSTRAINT EMPLOYEE_INFO_CHECK

ALTER TABLE EMPLOYEE_INFO ADD CONSTRAINT EMPLOYEE_INFO_CHECK_VAL CHECK (SAL>6000)

ALTER TABLE EMPLOYEE_INFO MODIFY SAL NUMBER NOT NULL

ALTER TABLE EMPLOYEE_INFO DROP CONSTRAINT EMPLOYEE_INFO_CHECK_VAL

ALTER TABLE EMPLOYEE_INFO MODIFY SAL NUMBER CHECK (SAL>7000)



CREATE SEQUENCE EMP_SEQ_VAL_NEW
    MINVALUE 0
    MAXVALUE 20
    START WITH 1
    INCREMENT BY 1
    CACHE 5

SELECT EMP_SEQ_VAL_NEW.NEXTVAL FROM DUAL


--CREATING THE DEFAULT SEQUENCES 

CREATE SEQUENCE DEFAULT_SEQ

SELECT DEFAULT_SEQ.NEXTVAL FROM DUAL