
SELECT S.SALES_DATE , S.ORDER_ID, ST.S_TOTAL FROM SALES S ,
(
SELECT SALES_DATE , SUM(TOTAL_AMOUNT) AS S_TOTAL FROM 
SALES GROUP BY SALES_DATE
) ST
WHERE S.SALES_DATE=ST.SALES_DATE ;


SELECT * FROM SALES;

SELECT DISTINCT S.SALES_DATE, S.ORDER_ID,S.CUSTOMER_ID , ST.S_TAX
FROM SALES S,
(SELECT  SALES_DATE ,SUM(TAX_AMOUNT) AS S_TAX
FROM SALES GROUP BY SALES_DATE) ST
WHERE S.SALES_DATE=ST.SALES_DATE;

WITH ST AS
(
SELECT  SALES_DATE ,SUM(TAX_AMOUNT) AS S_TAX
FROM SALES GROUP BY SALES_DATE
)
SELECT DISTINCT S.SALES_DATE, S.ORDER_ID,S.CUSTOMER_ID , ST.S_TAX
FROM SALES S,ST
WHERE S.SALES_DATE=ST.SALES_DATE;


SELECT DISTINCT S.SALES_DATE, S.ORDER_ID,S.CUSTOMER_ID
(
SELECT SUM(TAX_AMOUNT)
FROM SALES
)
FROM SALES S,ST
WHERE S.SALES_DATE=ST.SALES_DATE;





CREATE INDEX SALES_INDEX ON SALES (ORDER_ID)


ALTER INDEX SALES_INDEX RENAME TO SALES2_INDEX;


DROP INDEX SALES2_INDEX;

SELECT * FROM  SALES WHERE TAX_AMOUNT=170;

SELECT * FROM  SALES WHERE ORDER_ID=1269; 












