
SELECT * FROM SALES;


--NORMAL SUB QUERY WITH ONE RESULT FROM SUBQUERY--

SELECT * FROM SALES WHERE CUSTOMER_ID = (
SELECT CUSTOMER_ID FROM SALES WHERE ORDER_ID=1269
);


--NORMAL SUB QUERY WITH MULTIPLE  RESULT FROM SUBQUERY--

SELECT * FROM SALES WHERE CUSTOMER_ID IN  (
SELECT CUSTOMER_ID FROM SALES WHERE ORDER_ID=1271
);



--NORMAL SUB QUERY WITH PAIRWISE RESULT--

SELECT * FROM SALES S WHERE (ORDER_ID,CUSTOMER_ID) IN
(
SELECT ORDER_ID,CUSTOMER_ID FROM SALES WHERE SALES_DATE='1-jan-2015'
);


--NORMAL SUB QUERY WITH  NON PAIRWISE RESULT--

SELECT  * FROM SALES WHERE ORDER_ID IN
(
SELECT ORDER_ID FROM SALES WHERE SALES_DATE='1-jan-2015'
)
AND CUSTOMER_ID IN
(
SELECT CUSTOMER_ID FROM SALES WHERE SALES_DATE='1-jan-2015'
);





---Here we are using the Sub Query Along with WITH Statement----

---This is an Alternative to SUBQUERY WITH FORM CLAUSE ------

WITH ST AS (
SELECT  DISTINCT SALES_DATE AS S_DATE,  SUM(ST1.TOTAL_AMOUNT) AS S_TOTAL
FROM SALES ST1 GROUP BY SALES_DATE
)
SELECT DISTINCT S.SALES_DATE, S.TOTAL_AMOUNT,S.ORDER_ID, ST.S_TOTAL
FROM SALES S, ST 
WHERE S.SALES_DATE=ST.S_DATE ORDER BY S.SALES_DATE;

--SUB QUERY WITH SCALER---

SELECT S.SALES_DATE,S.ORDER_ID,S.PRODUCT_ID,
(
--This is a Subquery  with in select statement but should return only one value for every coulmn value in the row--
--Hence For that we are using the Aggregare Function Max--

SELECT MAX(ST.TOTAL_AMOUNT) FROM SALES ST

) AS ST2
FROM SALES S;





