/*USAGE OF SUBSTITUTION AND BIND VALUES */

SET DEFINE ON

SELECT * FROM SALES;

DEFINE P_ID=10

PROMPT &P_ID

SELECT * FROM SALES WHERE PRODUCT_ID=&P_ID

ACCEPT C_ID PROMPT "PROVIDE YOUR CUSTOMER_ID"

PROMPT &C_ID

SELECT * FROM SALES WHERE ORDER_ID='&O_ID';

SELECT * FROM SALES WHERE UNIT_PRICE='&U_NO' AND QUANTITY_VALUE=&&U_NO 




