--here creating SYNONYM for the sales table so the integrety can be maintained--
CREATE SYNONYM SALES_SYNO  
FOR SALES;
--fetching the value from the synonym ---
SELECT *  FROM SALES_SYNO
--deleting the synonymns----
DROP SYNONYM SALES_SYNO;

--here also we will be creating the swquence which will help im creating the sequence and help in delivering the sequesces
CREATE  SEQUENCE SALES_SQ
MINVALUE 1
MAXVALUE 100
START WITH 1
INCREMENT BY 1
CACHE 10;

---WE CAN FETCH THE CURRENT AND THE NEXT VALUE IN THE SEQUENCE AS-----

SELECT SALES_SQ.NEXTVAL FROM DUAL;
SELECT SALES_SQ.CURRVAL FROM DUAL;

---USING THE SEQUENCE CREATING THE TABLE AND INSERTING THE PRIMARY KEY CONSTRAINT USING THE SEQUENCE--

CREATE TABLE EQUIPMENT(
ID NUMBER,
SNE_ID NUMBER,
TRS_AREA VARCHAR2(10)
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT PK_ID PRIMARY KEY(ID);

CREATE SEQUENCE EQIP_SEQ
MINVALUE 1
MAXVALUE 10
START WITH 1
INCREMENT BY 1
CACHE 5;


INSERT INTO EQUIPMENT (ID,SNE_ID,TRS_AREA) VALUES (EQIP_SEQ.NEXTVAL, 333333,'L/NWS');


